### ISSUE TITLE
I get an error when I try to run. (just nft-do-it)

### ISSUE THREAD

**Issue by furkancelik** [kenobijon/nft-vote-polymer#1]
```
git clone https://github.com/kenobijon/nft-vote-polymer.git
cd nft-vote-polymer
just install
```
After running the commands (I edit my env file before doing just install).

```
just nft-do-it
```

After the command, I get an error like the following..

```
 just nft-do-it
echo "Running the full E2E flow..."
Running the full E2E flow...
just set-contracts optimism IbcBallot false && just set-contracts base IbcProofOfVoteNFT false
echo "Updating config.json with contract type..."
Updating config.json with contract type...
node scripts/private/_set-contracts-config.js optimism IbcBallot false
/root/node/polymer/nft-vote-polymer/node_modules/hardhat/internal/core/config/config-validation.js:256
    throw new errors_1.HardhatError(errors_list_1.ERRORS.GENERAL.INVALID_CONFIG, { errors: errorList });
    ^

HardhatError: HH8: There's one or more errors in your config file:

  * Invalid account: #0 for network: base - Expected string, received undefined
  * Invalid account: #0 for network: optimism - Expected string, received undefined

To learn more about Hardhat's configuration, please go to https://hardhat.org/config/
    at validateConfig (/root/node/polymer/nft-vote-polymer/node_modules/hardhat/internal/core/config/config-validation.js:256:11)
    at loadConfigAndTasks (/root/node/polymer/nft-vote-polymer/node_modules/hardhat/internal/core/config/config-loading.js:79:5)
    at Object.<anonymous> (/root/node/polymer/nft-vote-polymer/node_modules/hardhat/internal/lib/hardhat-lib.js:30:84)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/root/node/polymer/nft-vote-polymer/scripts/private/_helpers.js:3:13) {
  parent: undefined,
  _stack: "HardhatError: HH8: There's one or more errors in your config file:\n" +
    '\n' +
    '  * Invalid account: #0 for network: base - Expected string, received undefined\n' +
    '  * Invalid account: #0 for network: optimism - Expected string, received undefined\n' +
    '\n' +
    "To learn more about Hardhat's configuration, please go to https://hardhat.org/config/\n" +
    '    at validateConfig (/root/node/polymer/nft-vote-polymer/node_modules/hardhat/internal/core/config/config-validation.js:256:11)\n' +
    '    at loadConfigAndTasks (/root/node/polymer/nft-vote-polymer/node_modules/hardhat/internal/core/config/config-loading.js:79:5)\n' +
    '    at Object.<anonymous> (/root/node/polymer/nft-vote-polymer/node_modules/hardhat/internal/lib/hardhat-lib.js:30:84)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1356:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1197:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:1013:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1225:19)\n' +
    '    at require (node:internal/modules/helpers:177:18)\n' +
    '    at Object.<anonymous> (/root/node/polymer/nft-vote-polymer/scripts/private/_helpers.js:3:13)',
  errorDescriptor: {
    number: 8,
    message: "There's one or more errors in your config file:\n" +
      '\n' +
      '%errors%\n' +
      '\n' +
      "To learn more about Hardhat's configuration, please go to https://hardhat.org/config/",
    title: 'Invalid Hardhat config',
    description: 'You have one or more errors in your config file.\n' +
      '\n' +
      'Check the error message for details, or go to the [documentation](https://hardhat.org/config/) to learn more.',
    shouldBeReported: false
  },
  number: 8,
  messageArguments: {
    errors: '  * Invalid account: #0 for network: base - Expected string, received undefined\n' +
      '  * Invalid account: #0 for network: optimism - Expected string, received undefined'
  },
  _isHardhatError: true
}

Node.js v20.11.1
error: Recipe `set-contracts` failed on line 30 with exit code 1
error: Recipe `nft-do-it` failed on line 97 with exit code 1
```

<img width="1377" alt="Ekran Resmi 2024-03-16 00 47 08" src="https://github.com/kenobijon/nft-vote-polymer/assets/6446228/dea2f12c-a401-4617-a1cb-e4d52066cae4">

What is the reason for this? I got such an error when I tried to test it.

**Comment by kenobijon** [comment]
@furkancelik Sent some feedback in Discrod but it seems you need to add your private key to `.env` file

**Comment by furkancelik** [comment]
I'll change my env file. I sent a packet to ibc with my old env file before. api is working. I couldn't run it even though I changed env. 

I am running just install command first yes. 

I get the following output in just install command;

```
just install
echo "Installing dependencies"
Installing dependencies
npm install

up to date, audited 587 packages in 850ms

97 packages are looking for funding
  run `npm fund` for details

2 vulnerabilities (1 low, 1 moderate)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
forge install --shallow
Usage: forge [OPTIONS] COMMAND [ARGS]...
Try 'forge --help' for help.
```

<img width="988" alt="Ekran Resmi 2024-03-16 01 06 33" src="https://github.com/kenobijon/nft-vote-polymer/assets/6446228/bbb4d9ce-e2f6-47cb-ade6-ba1d26e2be28">

**Comment by kenobijon** [comment]
@furkancelik have you installed rust and just and forge? See the prerequisites section for everything you need to install on your machine to run
